version: "3"
services:
  yourtext:
    image: "careywong/yourtext:latest"
    container_name: yourtext
    env_file: .env
    environment:
      - "GIN_MODE=release"
      - "YOURTEXT_MINIO_ENDPOINT=yourtext-minio:9000"
    ports:
      - "${YOURTEXT_APP_PORT}:8080"
    depends_on:
      - yourtext-minio

  yourtext-minio:
    image: "minio/minio:latest"
    container_name: yourtext-minio
    volumes:
      - ./data/minio:/data
    expose:
      - "9000"
    environment:
      - "MINIO_ROOT_USER=${YOURTEXT_MINIO_ACCESS_KEY}"
      - "MINIO_ROOT_PASSWORD=${YOURTEXT_MINIO_SECRET_KEY}"
      - "MINIO_ADDRESS=:9000"
    command: server /data
